/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  safelist: [
    'typing-dot-1','typing-dot-2','typing-dot-3',
    'pulse-dot','no-scrollbar','green-slider',
  ],
  theme: {
    extend: {
      fontFamily: {
        cormorant: ['var(--font-cormorant)'],
        jost:      ['var(--font-jost)'],
        // Legacy aliases so old classes don't break:
        playfair:  ['var(--font-cormorant)'],
        inter:     ['var(--font-jost)'],
        dm:        ['var(--font-jost)'],
      },
      borderRadius: {
        DEFAULT: '3px',
        lg:  '3px',
        md:  '3px',
        sm:  '2px',
        xl:  '4px',
        '2xl': '4px',
        '3xl': '4px',
        '4xl': '4px',
        pill: '3px',
        full: '9999px',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card:{ DEFAULT:'hsl(var(--card))',foreground:'hsl(var(--card-foreground))' },
        popover:{ DEFAULT:'hsl(var(--popover))',foreground:'hsl(var(--popover-foreground))' },
        primary:{ DEFAULT:'hsl(var(--primary))',foreground:'hsl(var(--primary-foreground))' },
        secondary:{ DEFAULT:'hsl(var(--secondary))',foreground:'hsl(var(--secondary-foreground))' },
        muted:{ DEFAULT:'hsl(var(--muted))',foreground:'hsl(var(--muted-foreground))' },
        accent:{ DEFAULT:'hsl(var(--accent))',foreground:'hsl(var(--accent-foreground))' },
        destructive:{ DEFAULT:'hsl(var(--destructive))',foreground:'hsl(var(--destructive-foreground))' },
        border:'hsl(var(--border))',
        input:'hsl(var(--input))',
        ring:'hsl(var(--ring))',

        /* ── Brand palette ── */
        'brand':        '#3D5A3E',
        'brand-light':  '#E8EFE8',
        'brand-mid':    '#6B8F6C',
        'brand-dark':   '#2C3E2D',
        'accent-warm':  '#C8A882',
        'page-bg':      '#FFFFFF',
        'section-alt':  '#F7F7F5',
        'card-bg':      '#FFFFFF',
        'text-primary': '#1A1F1A',
        'text-secondary':'#5C6B5C',
        'text-muted':   '#9AAA9A',
        'border-default':'#E2E8E2',
        'border-em':    '#3D5A3E',
        'danger':       '#C0392B',

        /* Legacy aliases — keep old components from breaking */
        'hot-pink':    '#3D5A3E',
        'soft-pink':   '#6B8F6C',
        'blush-light': '#E8EFE8',
        'petal':       '#F7F7F5',
        'brand-plum':  '#3D5A3E',
        'deep-plum':   '#2C3E2D',
        'baby-pink':   '#6B8F6C',
        'deep-rose':   '#3D5A3E',
        'blush':       '#E8EFE8',
        'card-pink':   '#FFFFFF',
        'border-pink': '#E2E8E2',
        'rose-gold':   '#C8A882',
        'dusty-pink':  '#6B8F6C',
        'deep-mauve':  '#3D5A3E',
        'warm-charcoal':'#1A1F1A',
        'warm-gray':   '#5C6B5C',
        'peach-bg':    '#F7F7F5',
        'lavender-chat':'#E8EFE8',
        'rose-chat':   '#E8EFE8',

        chart:{
          '1':'#3D5A3E',
          '2':'#C8A882',
          '3':'#6B8F6C',
          '4':'#E8EFE8',
          '5':'#E2E8E2',
        },
        sidebar:{
          DEFAULT:'hsl(var(--sidebar-background))',
          foreground:'hsl(var(--sidebar-foreground))',
          primary:'hsl(var(--sidebar-primary))',
          'primary-foreground':'hsl(var(--sidebar-primary-foreground))',
          accent:'hsl(var(--sidebar-accent))',
          'accent-foreground':'hsl(var(--sidebar-accent-foreground))',
          border:'hsl(var(--sidebar-border))',
          ring:'hsl(var(--sidebar-ring))',
        },
      },
      boxShadow: {
        'card':      '0 2px 16px rgba(61,90,62,0.08)',
        'card-hover':'0 8px 32px rgba(61,90,62,0.14)',
        'glow':      '0 2px 16px rgba(61,90,62,0.08)',
        'glow-lg':   '0 8px 32px rgba(61,90,62,0.14)',
        'glow-sm':   '0 1px 8px rgba(61,90,62,0.06)',
        'btn':       '0 4px 14px rgba(61,90,62,0.20)',
        'plum':      '0 4px 16px rgba(61,90,62,0.16)',
      },
      keyframes: {
        'accordion-down':{from:{height:'0'},to:{height:'var(--radix-accordion-content-height)'}},
        'accordion-up':{from:{height:'var(--radix-accordion-content-height)'},to:{height:'0'}},
      },
      animation: {
        'accordion-down':'accordion-down 0.2s ease-out',
        'accordion-up':'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
